"""change order table restructure

Revision ID: cc679c7bf62f
Revises: 4f52225384bb
Create Date: 2025-03-17 23:34:08.495641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc679c7bf62f'
down_revision: Union[str, None] = '4f52225384bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_images', sa.String(), nullable=True))
    op.drop_constraint('orders_item_id_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'order_date')
    op.drop_column('orders', 'item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('order_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('status', postgresql.ENUM('PENDING', 'SHIPPED', 'DELIVERED', 'RETURNED', 'REFUNDED', 'ESCALATED', name='orderstatusenum'), autoincrement=False, nullable=True))
    op.create_foreign_key('orders_item_id_fkey', 'orders', 'items', ['item_id'], ['id'])
    op.drop_column('orders', 'order_images')
    # ### end Alembic commands ###
